MAX_CORES = 128
NEURONS_PER_CORE = 1024
NEURON_BITS = 10
DATA_WIDTH = 16
WEIGHT_MIN = -32768
WEIGHT_MAX = 32767
COMPARTMENTS = 4

POOL_DEPTH = 32768
POOL_ADDR_BITS = 15
INDEX_WIDTH = 25
COUNT_BITS = 10

ROUTE_FANOUT = 8
ROUTE_SLOT_BITS = 3

REV_FANIN = 32
REV_SLOT_BITS = 5

MAX_FANOUT = 32

DEFAULT_THRESHOLD = 1000
DEFAULT_LEAK = 3
DEFAULT_RESTING = 0
DEFAULT_REFRAC = 3
DEFAULT_DEND_THRESHOLD = 0

PARAM_THRESHOLD = 0
PARAM_LEAK = 1
PARAM_RESTING = 2
PARAM_REFRAC = 3
PARAM_DEND_THRESHOLD = 4
PARAM_NOISE_CFG = 5
PARAM_TAU1 = 6
PARAM_TAU2 = 7

TRACE_MAX = 100
TRACE_DECAY = 3
LEARN_SHIFT = 3
GRADE_SHIFT = 7
WEIGHT_MAX_STDP = 2000
WEIGHT_MIN_STDP = 0

DEFAULT_NOISE_CONFIG = 0
NOISE_LFSR_SEED = 0xACE1
NOISE_LFSR_TAPS = 0xB400

DEFAULT_TAU1 = 3
DEFAULT_TAU2 = 4

MAX_DELAY = 63
DEFAULT_DELAY = 0
DELAY_QUEUE_BUCKETS = 64

FMT_SPARSE = 0
FMT_DENSE = 1
FMT_POP = 2
VALID_FORMATS = {'sparse': FMT_SPARSE, 'dense': FMT_DENSE, 'pop': FMT_POP}

REWARD_SHIFT = 7
ELIG_DECAY_SHIFT = 3
ELIG_MAX = 1000

DEFAULT_CLUSTER_SIZE = 4
GLOBAL_ROUTE_SLOTS = 4

MICROCODE_DEPTH = 64
MICROCODE_LTD_START = 0
MICROCODE_LTP_START = 16

CMD_PROG_POOL = 0x01
CMD_PROG_ROUTE = 0x02
CMD_STIMULUS = 0x03
CMD_RUN = 0x04
CMD_STATUS = 0x05
CMD_LEARN_CFG = 0x06
CMD_PROG_NEURON = 0x07
CMD_PROG_INDEX = 0x08
CMD_REWARD = 0x09
CMD_PROG_DELAY = 0x0A
CMD_PROG_LEARN = 0x0C
CMD_PROG_GLOBAL_ROUTE = 0x10
CMD_PROG_CONN = CMD_PROG_POOL
