class NeurocoreError(Exception): ...

class NetworkTooLargeError(NeurocoreError): ...

class PoolOverflowError(NeurocoreError): ...

FanoutOverflowError = PoolOverflowError

class RouteOverflowError(NeurocoreError): ...

class WeightOutOfRangeError(NeurocoreError): ...

class InvalidParameterError(NeurocoreError): ...

class PlacementError(NeurocoreError): ...

class ChipCommunicationError(NeurocoreError): ...
